### ISSUE TITLE
About 1 hours

### ISSUE THREAD

**Issue by MartkCz** [jimmiw/php-time-ago#79] opened 2018-12-10 20:57 UTC
DateInterval dump:
```php
y => 0
m => 0
d => 0
h => 1
i => 50
s => 25
f => 0.90637199999999996
```

but rule 5 is used => about 1 hours

**Comment by dhutapratama** [comment] 2019-04-07 12:18
I really do not know this issue purpose, about what issue or any details or how to reproduce.

And in my brain trying to translate that, is it about using s or not in "hours" word?

Because 1 is must using hour? Or what?

**Comment by MartkCz** [comment] 2019-04-08 12:46
When I use 

```php
var_dump((new TimeAgo())->inWords(new \DateTime('- 110 minutes')));
```

it prints `1 hours ago` expected result is `2 hours ago` or `1 hour ago`

**Comment by jimmiw** [comment] 2019-04-08 14:07
this issue is now fixed and the unit tests have been updated to reflect this.

**Closed by jimmiw** 2019-04-08 14:07 UTC
